name: osemosys
channels:
- conda-forge
dependencies:
  - python ==3.10
  - ipykernel
  - pyomo
  - openpyxl == 3.0.10
  - numpy ==1.24.3
  - pandas==2.1.0
  - vincent
  - plotly
  - highs
  - pint <0.24
  - scipy ==1.10.1


# installing the scip solver:
  - gcg 
  - papilo
  - scip
  - soplex
  - zimpl

# pip dependencies:
  - pip >= 9.0.1
  - pip:
    - highspy
